### ISSUE TITLE
RangeError: maximum stack size exceeded error (refers to #18)

### ISSUE THREAD

**Issue by porotkin** [stoplightio/json-schema-tree#19]
Due to the recent changes, when the schema is being defined as a ref to itself (recursive) with an overridden `description` property, it causes the StackOverflow error in json-schema-tree.

*Example:*
```language=yaml
Cat:
  type: object
  properties:
    parents:
      type: array
      items:
        $ref: '#/components/schemas/Cat'
        description: Cat's parents
```

## Context

This causes the `Error: Stack size exceeded` rendering on HttpOperation node where such schema is referenced

## Current Behavior

![image](https://user-images.githubusercontent.com/34237389/205042269-3bafe395-3b20-4e74-a072-50b79b553f98.png)

## Expected Behavior

The schema is rendered correctly and doesn't make the page to load till the stack size is exceeded (provoking the browser page unresponsiveness)

## Possible Workaround/Solution

#18 caused this
`newFragment = { ...newFragment };` - this is the line in `walker.js` file causing the referential inequality that later as far as I grasped leads to the infinite ref resolving

## Steps to Reproduce

1. just copy such schema to any existent OAS specification and try to open it in Elements

## Environment

- Version used: 2.2.2
- Environment name and version (e.g. `Chrome: 39`, `node.js: 5.4`): Chrome latest
- Operating System and version (desktop or mobile): macOS
- Link to your environment/workspace/project: -

**Comment by porotkin** [comment]
@P0lip, please, help with the issue. I see the only one solution at the moment - it's not to clone the object. But as you've mentioned in #18, it's a bad thing and can probably lead to a flunky behavior

**Comment by tintin92350** [comment]
Hello ! We still have this problem. Has anyone found a solution?

**Comment by P0lip** [comment]
@porotkin https://github.com/stoplightio/json-schema-tree/pull/25 should address your issue.
LMK in case it's still broken.
